// <auto-generated />
using System;
using AssetManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementSystem.Migrations
{
    [DbContext(typeof(AssetManagementDBContext))]
    [Migration("20260329202927_InitialDbSetup")]
    partial class InitialDbSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagementSystem.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'SOFTHARD-' + CAST(Id AS VARCHAR)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            SerialNumber = "SN123456",
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desktop",
                            SerialNumber = "SN654321",
                            StatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Printer",
                            SerialNumber = "SN789012",
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.AssetSoftware", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareLicenseId")
                        .HasColumnType("int");

                    b.HasKey("AssetId", "SoftwareLicenseId");

                    b.HasIndex("SoftwareLicenseId");

                    b.ToTable("AssetSoftwares");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.SoftwareLicense", b =>
                {
                    b.Property<int>("SoftwareLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareLicenseId"));

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoftwareLicenseId");

                    b.ToTable("SoftwareLicenses");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "Available"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "Assigned"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Retired"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.WarrantyCard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WarrantyCards");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Asset", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Employee", "Employee")
                        .WithMany("Assets")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("AssetManagementSystem.Models.Status", "Status")
                        .WithMany("Assets")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.AssetSoftware", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Asset", "Asset")
                        .WithMany("AssetSoftwares")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagementSystem.Models.SoftwareLicense", "SoftwareLicense")
                        .WithMany("AssetSoftwares")
                        .HasForeignKey("SoftwareLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SoftwareLicense");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.WarrantyCard", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Asset", "Asset")
                        .WithOne("WarrantyCard")
                        .HasForeignKey("AssetManagementSystem.Models.WarrantyCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Asset", b =>
                {
                    b.Navigation("AssetSoftwares");

                    b.Navigation("WarrantyCard")
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.SoftwareLicense", b =>
                {
                    b.Navigation("AssetSoftwares");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Status", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
